package id.andriawan.cofinance.data.crypto

import kotlinx.cinterop.COpaquePointer
import kotlinx.cinterop.CPointed
import kotlinx.cinterop.CPointer
import kotlinx.cinterop.ExperimentalForeignApi
import kotlinx.cinterop.addressOf
import kotlinx.cinterop.alloc
import kotlinx.cinterop.convert
import kotlinx.cinterop.get
import kotlinx.cinterop.memScoped
import kotlinx.cinterop.ptr
import kotlinx.cinterop.reinterpret
import kotlinx.cinterop.usePinned
import kotlinx.cinterop.value
import platform.CoreFoundation.CFDataCreate
import platform.CoreFoundation.CFDataGetBytePtr
import platform.CoreFoundation.CFDataGetLength
import platform.CoreFoundation.CFDataRef
import platform.CoreFoundation.CFDataRefVar
import platform.CoreFoundation.CFDictionaryAddValue
import platform.CoreFoundation.CFDictionaryCreateMutable
import platform.CoreFoundation.CFDictionaryGetValue
import platform.CoreFoundation.CFDictionaryRef
import platform.CoreFoundation.CFErrorCopyDescription
import platform.CoreFoundation.CFErrorGetCode
import platform.CoreFoundation.CFErrorRefVar
import platform.CoreFoundation.CFRelease
import platform.CoreFoundation.CFRetain
import platform.CoreFoundation.CFStringRef
import platform.CoreFoundation.CFTypeRefVar
import platform.CoreFoundation.kCFAllocatorDefault
import platform.CoreFoundation.kCFBooleanTrue
import platform.CoreFoundation.kCFTypeDictionaryKeyCallBacks
import platform.CoreFoundation.kCFTypeDictionaryValueCallBacks
import platform.Foundation.CFBridgingRelease
import platform.Foundation.CFBridgingRetain
import platform.Foundation.NSNumber
import platform.Foundation.numberWithInt
import platform.Security.SecAccessControlCreateFlags
import platform.Security.SecAccessControlCreateWithFlags
import platform.Security.SecAccessControlRef
import platform.Security.SecItemAdd
import platform.Security.SecItemCopyMatching
import platform.Security.SecItemDelete
import platform.Security.SecKeyCopyExternalRepresentation
import platform.Security.SecKeyCopyKeyExchangeResult
import platform.Security.SecKeyCopyPublicKey
import platform.Security.SecKeyCreateRandomKey
import platform.Security.SecKeyCreateWithData
import platform.Security.SecKeyRef
import platform.Security.SecKeyRefVar
import platform.Security.SecRandomCopyBytes
import platform.Security.errSecDuplicateItem
import platform.Security.errSecItemNotFound
import platform.Security.errSecSuccess
import platform.Security.kSecAccessControlPrivateKeyUsage
import platform.Security.kSecAttrAccessControl
import platform.Security.kSecAttrAccessible
import platform.Security.kSecAttrAccessibleWhenUnlockedThisDeviceOnly
import platform.Security.kSecAttrAccount
import platform.Security.kSecAttrApplicationTag
import platform.Security.kSecAttrIsPermanent
import platform.Security.kSecAttrKeyClass
import platform.Security.kSecAttrKeyClassPrivate
import platform.Security.kSecAttrKeyClassPublic
import platform.Security.kSecAttrKeySizeInBits
import platform.Security.kSecAttrKeyType
import platform.Security.kSecAttrKeyTypeECSECPrimeRandom
import platform.Security.kSecAttrService
import platform.Security.kSecAttrTokenID
import platform.Security.kSecAttrTokenIDSecureEnclave
import platform.Security.kSecClass
import platform.Security.kSecClassGenericPassword
import platform.Security.kSecClassKey
import platform.Security.kSecKeyAlgorithmECDHKeyExchangeStandard
import platform.Security.kSecPrivateKeyAttrs
import platform.Security.kSecRandomDefault
import platform.Security.kSecReturnAttributes
import platform.Security.kSecReturnData
import platform.Security.kSecReturnRef
import platform.Security.kSecValueData

/** Application tag of the device key pair's Keychain item. */
internal const val DEVICE_KEY_TAG: String = "id.andriawan.cofinance.crypto.device-key"

/** Service of the device secret's generic password item. */
internal const val DEVICE_SECRET_SERVICE: String = "id.andriawan.cofinance.crypto"

/** Account of the device secret's generic password item. */
internal const val DEVICE_SECRET_ACCOUNT: String = "device-secret"

@OptIn(ExperimentalForeignApi::class)
actual fun createDeviceKeyVault(): DeviceKeyVault = KeychainDeviceKeyVault()

/**
 * A [DeviceKeyVault] over the iOS Keychain, with the key pair created inside the Secure Enclave
 * wherever the hardware offers one.
 *
 * ## What "non-extractable" means here, and where it stops being true
 *
 * On a physical device the P-256 private key is generated by and lives inside the Secure Enclave:
 * the Keychain item is a reference to hardware-held material, `SecItemCopyMatching` with
 * `kSecReturnData` cannot produce its bytes, and ECDH runs inside the Enclave. That is the
 * guarantee Decision 2 of the design buys by choosing P-256 — the curve follows the hardware.
 *
 * **The simulator has no Secure Enclave.** `SecKeyCreateRandomKey` with
 * `kSecAttrTokenIDSecureEnclave` fails there, so [createKeyPair] falls back to an ordinary
 * Keychain-resident software key. That fallback keeps every other property — device-restricted
 * through `kSecAttrAccessibleWhenUnlockedThisDeviceOnly`, excluded from backups, not exported by
 * this class — but the private key is software held by the Keychain daemon rather than sealed in
 * hardware. Simulator behaviour is therefore **not** evidence of the device guarantee, and any test
 * asserting hardware backing must run on a physical device. [isSecureEnclaveBacked] reports which
 * of the two a given installation actually got, so the distinction is observable rather than
 * assumed.
 *
 * ## Lifetime of the stored material
 *
 * Both the key pair and the device secret are created on first use and then persist: they survive
 * app launches and app updates, and — because iOS Keychain items are not removed when an app is
 * deleted — they can outlive an uninstall and be found again by a reinstall. That persistence is
 * deliberate, and is what Decision 3 relies on when it ties the failed-attempt counter to the
 * device key's lifetime so that reinstalling cannot reset it. They are removed only by
 * [destroyKeyMaterial], by erasing the device, or by iOS discarding the Keychain (restoring the
 * device from a backup does not carry them over: `ThisDeviceOnly` items are excluded from backups
 * and from migration to a new device).
 *
 * The device secret is a 32-byte random value in a generic password item. Unlike the private key it
 * is readable in process, which the interface documents and the PIN composition requires; what it
 * guarantees is that the value never leaves this device.
 */
@OptIn(ExperimentalForeignApi::class)
internal class KeychainDeviceKeyVault(
    internal val keyTag: String = DEVICE_KEY_TAG,
    internal val secretService: String = DEVICE_SECRET_SERVICE,
    internal val secretAccount: String = DEVICE_SECRET_ACCOUNT
) : DeviceKeyVault {

    override suspend fun devicePublicKey(): ByteArray {
        val privateKey = findPrivateKey() ?: createPrivateKey()
        try {
            return exportPublicKey(privateKey)
        } finally {
            CFRelease(privateKey)
        }
    }

    override suspend fun sharedSecretWith(peerPublicKey: ByteArray): ByteArray {
        if (peerPublicKey.size != DeviceKeyVault.PUBLIC_KEY_SIZE ||
            peerPublicKey[0] != UNCOMPRESSED_POINT_TAG
        ) {
            throw DeviceKeyVaultException(
                "Peer public key is not a ${DeviceKeyVault.PUBLIC_KEY_SIZE}-byte uncompressed " +
                    "SEC 1 P-256 point"
            )
        }
        val privateKey = findPrivateKey() ?: createPrivateKey()
        try {
            return keyExchange(privateKey, peerPublicKey)
        } finally {
            CFRelease(privateKey)
        }
    }

    override suspend fun deviceSecret(): ByteArray =
        readDeviceSecret() ?: createDeviceSecret() ?: readDeviceSecret()
        ?: throw DeviceKeyVaultException("Device secret disappeared immediately after creation")

    override suspend fun destroyKeyMaterial() {
        cfOwning { owner ->
            val keyQuery = owner.dictionaryOf(
                listOf(
                    kSecClass to kSecClassKey,
                    kSecAttrApplicationTag to owner.dataOf(keyTag.encodeToByteArray(), "key tag")
                )
            )
            deleteMatching(keyQuery, "device key")

            val secretQuery = owner.dictionaryOf(
                listOf(
                    kSecClass to kSecClassGenericPassword,
                    kSecAttrService to owner.stringOf(secretService),
                    kSecAttrAccount to owner.stringOf(secretAccount)
                )
            )
            deleteMatching(secretQuery, "device secret")
        }
    }

    /**
     * Reports whether the stored key pair actually lives in the Secure Enclave.
     *
     * `false` means the Keychain-resident fallback is in use — the expected result on the simulator
     * and the reason simulator runs cannot stand in for a hardware check.
     */
    internal fun isSecureEnclaveBacked(): Boolean = cfOwning { owner ->
        memScoped {
            val query = owner.dictionaryOf(
                listOf(
                    kSecClass to kSecClassKey,
                    kSecAttrApplicationTag to owner.dataOf(keyTag.encodeToByteArray(), "key tag"),
                    kSecAttrKeyType to kSecAttrKeyTypeECSECPrimeRandom,
                    kSecAttrKeyClass to kSecAttrKeyClassPrivate,
                    kSecReturnAttributes to kCFBooleanTrue
                )
            )
            val found = alloc<CFTypeRefVar>()
            when (val status = SecItemCopyMatching(query, found.ptr)) {
                errSecSuccess -> Unit
                errSecItemNotFound -> throw DeviceKeyVaultException(
                    "No device key exists yet, so nothing backs it"
                )

                else -> throw DeviceKeyVaultException(
                    "Reading the device key attributes failed (OSStatus $status)"
                )
            }
            val attributes = found.value ?: return@memScoped false
            try {
                val tokenId = CFDictionaryGetValue(attributes.reinterpret(), kSecAttrTokenID)
                tokenId != null && tokenId.copyAsString() ==
                    kSecAttrTokenIDSecureEnclave.copyAsString()
            } finally {
                CFRelease(attributes)
            }
        }
    }

    private fun findPrivateKey(): SecKeyRef? = cfOwning { owner ->
        memScoped {
            val query = owner.dictionaryOf(
                listOf(
                    kSecClass to kSecClassKey,
                    kSecAttrApplicationTag to owner.dataOf(keyTag.encodeToByteArray(), "key tag"),
                    kSecAttrKeyType to kSecAttrKeyTypeECSECPrimeRandom,
                    kSecAttrKeyClass to kSecAttrKeyClassPrivate,
                    kSecReturnRef to kCFBooleanTrue
                )
            )
            val found = alloc<SecKeyRefVar>()
            when (val status = SecItemCopyMatching(query, found.ptr.reinterpret())) {
                errSecSuccess -> found.value
                errSecItemNotFound -> null
                else -> throw DeviceKeyVaultException(
                    "Keychain lookup for the device key failed (OSStatus $status)"
                )
            }
        }
    }

    private fun createPrivateKey(): SecKeyRef {
        val enclave = runCatching { createKeyPair(inSecureEnclave = true) }
        enclave.getOrNull()?.let { return it }
        // No Secure Enclave here — the simulator always lands on this branch, and so does any
        // device whose Enclave refuses the request. The key stays device-restricted and
        // unexported, but it is not hardware-sealed; see the class documentation.
        return try {
            createKeyPair(inSecureEnclave = false)
        } catch (fallbackFailure: DeviceKeyVaultException) {
            throw DeviceKeyVaultException(
                "Creating the device key failed in the Secure Enclave " +
                    "(${enclave.exceptionOrNull()?.message}) and in the Keychain " +
                    "(${fallbackFailure.message})",
                fallbackFailure
            )
        }
    }

    private fun createKeyPair(inSecureEnclave: Boolean): SecKeyRef = cfOwning { owner ->
        memScoped {
            val error = alloc<CFErrorRefVar>()
            // kSecAccessControlPrivateKeyUsage is what permits the Enclave to use the private key
            // for ECDH; kSecAttrAccessibleWhenUnlockedThisDeviceOnly is what keeps the item on this
            // device and out of every backup.
            val flags: SecAccessControlCreateFlags =
                if (inSecureEnclave) PRIVATE_KEY_USAGE_FLAG else NO_ACCESS_CONTROL_FLAGS
            val access: SecAccessControlRef = SecAccessControlCreateWithFlags(
                kCFAllocatorDefault,
                kSecAttrAccessibleWhenUnlockedThisDeviceOnly,
                flags,
                error.ptr
            ) ?: throw error.consume("Creating the device key access control failed")
            owner.own(access, "an access control")

            val privateAttributes = owner.dictionaryOf(
                listOf(
                    kSecAttrIsPermanent to kCFBooleanTrue,
                    kSecAttrApplicationTag to owner.dataOf(keyTag.encodeToByteArray(), "key tag"),
                    kSecAttrAccessControl to access
                )
            )
            val parameters = buildList {
                add(kSecAttrKeyType to kSecAttrKeyTypeECSECPrimeRandom)
                add(kSecAttrKeySizeInBits to owner.numberOf(P256_KEY_SIZE_IN_BITS))
                add(kSecPrivateKeyAttrs to privateAttributes)
                if (inSecureEnclave) add(kSecAttrTokenID to kSecAttrTokenIDSecureEnclave)
            }

            SecKeyCreateRandomKey(owner.dictionaryOf(parameters), error.ptr)
                ?: throw error.consume(
                    if (inSecureEnclave) {
                        "Creating the device key in the Secure Enclave failed"
                    } else {
                        "Creating the device key in the Keychain failed"
                    }
                )
        }
    }

    private fun exportPublicKey(privateKey: SecKeyRef): ByteArray = memScoped {
        val publicKey = SecKeyCopyPublicKey(privateKey)
            ?: throw DeviceKeyVaultException("The device key has no public half")
        try {
            val error = alloc<CFErrorRefVar>()
            val encoded = SecKeyCopyExternalRepresentation(publicKey, error.ptr)
                ?: throw error.consume("Exporting the device public key failed")
            try {
                // SecKeyCopyExternalRepresentation on an EC public key yields the uncompressed
                // SEC 1 point already, but the interface contract is a length, so check it.
                val bytes = encoded.toByteArray()
                if (bytes.size != DeviceKeyVault.PUBLIC_KEY_SIZE ||
                    bytes[0] != UNCOMPRESSED_POINT_TAG
                ) {
                    throw DeviceKeyVaultException(
                        "Device public key is ${bytes.size} bytes tagged 0x" +
                            "${bytes.firstOrNull()?.toUByte()?.toString(16)}, expected a " +
                            "${DeviceKeyVault.PUBLIC_KEY_SIZE}-byte point tagged 0x04"
                    )
                }
                bytes
            } finally {
                CFRelease(encoded)
            }
        } finally {
            CFRelease(publicKey)
        }
    }

    private fun keyExchange(privateKey: SecKeyRef, peerPublicKey: ByteArray): ByteArray =
        cfOwning { owner ->
            memScoped {
                val error = alloc<CFErrorRefVar>()
                val peerAttributes = owner.dictionaryOf(
                    listOf(
                        kSecAttrKeyType to kSecAttrKeyTypeECSECPrimeRandom,
                        kSecAttrKeyClass to kSecAttrKeyClassPublic,
                        kSecAttrKeySizeInBits to owner.numberOf(P256_KEY_SIZE_IN_BITS)
                    )
                )
                val peer = SecKeyCreateWithData(
                    owner.dataOf(peerPublicKey, "the peer public key"),
                    peerAttributes,
                    error.ptr
                ) ?: throw error.consume("Peer public key is not a P-256 point")
                owner.own(peer, "the peer key")

                // Standard ECDH: the raw agreement output, with no KDF applied. HKDF belongs to
                // the wrapping layer above, and both platforms must agree on that boundary.
                val secret = SecKeyCopyKeyExchangeResult(
                    privateKey,
                    kSecKeyAlgorithmECDHKeyExchangeStandard,
                    peer,
                    owner.dictionaryOf(emptyList()),
                    error.ptr
                ) ?: throw error.consume("ECDH with the device key failed")
                try {
                    secret.toByteArray()
                } finally {
                    CFRelease(secret)
                }
            }
        }

    private fun readDeviceSecret(): ByteArray? = cfOwning { owner ->
        memScoped {
            val query = owner.dictionaryOf(
                listOf(
                    kSecClass to kSecClassGenericPassword,
                    kSecAttrService to owner.stringOf(secretService),
                    kSecAttrAccount to owner.stringOf(secretAccount),
                    kSecReturnData to kCFBooleanTrue
                )
            )
            val found = alloc<CFDataRefVar>()
            when (val status = SecItemCopyMatching(query, found.ptr.reinterpret())) {
                errSecSuccess -> {
                    val data = found.value ?: return@memScoped null
                    try {
                        data.toByteArray()
                    } finally {
                        CFRelease(data)
                    }
                }

                errSecItemNotFound -> null
                else -> throw DeviceKeyVaultException(
                    "Keychain lookup for the device secret failed (OSStatus $status)"
                )
            }
        }
    }

    /** Returns the created secret, or `null` when another caller created it first. */
    private fun createDeviceSecret(): ByteArray? = cfOwning { owner ->
        val secret = randomBytes(DeviceKeyVault.DEVICE_SECRET_SIZE)
        val attributes = owner.dictionaryOf(
            listOf(
                kSecClass to kSecClassGenericPassword,
                kSecAttrService to owner.stringOf(secretService),
                kSecAttrAccount to owner.stringOf(secretAccount),
                kSecAttrAccessible to kSecAttrAccessibleWhenUnlockedThisDeviceOnly,
                kSecValueData to owner.dataOf(secret, "the device secret")
            )
        )
        when (val status = SecItemAdd(attributes, null)) {
            errSecSuccess -> secret
            errSecDuplicateItem -> null
            else -> throw DeviceKeyVaultException(
                "Storing the device secret in the Keychain failed (OSStatus $status)"
            )
        }
    }

    private fun deleteMatching(query: CFDictionaryRef, what: String) {
        val status = SecItemDelete(query)
        if (status != errSecSuccess && status != errSecItemNotFound) {
            throw DeviceKeyVaultException("Deleting the $what failed (OSStatus $status)")
        }
    }

    private fun randomBytes(size: Int): ByteArray {
        val bytes = ByteArray(size)
        val status = bytes.usePinned { pinned ->
            SecRandomCopyBytes(kSecRandomDefault, size.convert(), pinned.addressOf(0))
        }
        if (status != errSecSuccess) {
            throw DeviceKeyVaultException("Generating device secret bytes failed (status $status)")
        }
        return bytes
    }

    private companion object {
        const val UNCOMPRESSED_POINT_TAG: Byte = 0x04
        const val P256_KEY_SIZE_IN_BITS: Int = 256
        val PRIVATE_KEY_USAGE_FLAG: SecAccessControlCreateFlags =
            kSecAccessControlPrivateKeyUsage
        val NO_ACCESS_CONTROL_FLAGS: SecAccessControlCreateFlags = 0uL
    }
}

/**
 * Owns the CoreFoundation objects created while building a Keychain call and releases every one of
 * them when the call returns, so that a throw partway through cannot leak.
 */
@OptIn(ExperimentalForeignApi::class)
internal class CoreFoundationOwner {

    private val owned = mutableListOf<COpaquePointer>()

    fun <T : CPointed> own(value: CPointer<T>?, what: String): CPointer<T> {
        if (value == null) throw DeviceKeyVaultException("Allocating $what failed")
        owned += value
        return value
    }

    fun dictionaryOf(entries: List<Pair<CFStringRef?, COpaquePointer?>>): CFDictionaryRef {
        val dictionary = own(
            CFDictionaryCreateMutable(
                kCFAllocatorDefault,
                entries.size.convert(),
                kCFTypeDictionaryKeyCallBacks.ptr,
                kCFTypeDictionaryValueCallBacks.ptr
            ),
            "a Keychain query"
        )
        entries.forEach { (key, value) -> CFDictionaryAddValue(dictionary, key, value) }
        return dictionary
    }

    fun dataOf(bytes: ByteArray, what: String): CFDataRef = own(
        bytes.usePinned { pinned ->
            CFDataCreate(kCFAllocatorDefault, pinned.addressOf(0).reinterpret(), bytes.size.convert())
        },
        what
    )

    fun stringOf(value: String): COpaquePointer = own(CFBridgingRetain(value), "a Keychain string")

    fun numberOf(value: Int): COpaquePointer =
        own(CFBridgingRetain(NSNumber.numberWithInt(value)), "a Keychain number")

    fun releaseAll() {
        owned.forEach { CFRelease(it) }
        owned.clear()
    }
}

@OptIn(ExperimentalForeignApi::class)
internal inline fun <R> cfOwning(block: (CoreFoundationOwner) -> R): R {
    val owner = CoreFoundationOwner()
    try {
        return block(owner)
    } finally {
        owner.releaseAll()
    }
}

/** Turns a `CFError` out-parameter into a [DeviceKeyVaultException], releasing the error. */
@OptIn(ExperimentalForeignApi::class)
private fun CFErrorRefVar.consume(message: String): DeviceKeyVaultException {
    val error = value ?: return DeviceKeyVaultException(message)
    val code = CFErrorGetCode(error)
    val description = CFErrorCopyDescription(error)
    val detail = CFBridgingRelease(description) as? String
    CFRelease(error)
    value = null
    return DeviceKeyVaultException("$message (CFError $code${detail?.let { ": $it" }.orEmpty()})")
}

/**
 * Reads a borrowed `CFString` as a Kotlin string without taking ownership of it: the retain
 * balances the release that `CFBridgingRelease` performs when it hands the object to ARC.
 */
@OptIn(ExperimentalForeignApi::class)
internal fun COpaquePointer?.copyAsString(): String? {
    val value = this ?: return null
    CFRetain(value)
    return CFBridgingRelease(value) as? String
}

@OptIn(ExperimentalForeignApi::class)
private fun CFDataRef.toByteArray(): ByteArray {
    val length = CFDataGetLength(this).toInt()
    if (length == 0) return ByteArray(0)
    val bytes = CFDataGetBytePtr(this)
        ?: throw DeviceKeyVaultException("A Keychain value of $length bytes had no contents")
    return ByteArray(length) { index -> bytes[index].toByte() }
}
