# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(
        task: "test",
        gradle_path: "../gradlew"
    )
  end

  desc "Deploy a new development version to firebase distribution"
  lane :distribute do
    gradle(
        task: ":android-app:assemble",
        build_type: "Debug",
        gradle_path: "../gradlew"
    )

    changelog = changelog_from_git_commits(
      pretty: "- %s", # Format each commit message with a bullet point
      merge_commit_filtering: "exclude_merges" # Exclude merge commits for cleaner notes
    )

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      android_artifact_path: "./build/outputs/apk/debug/android-app-debug.apk",
      groups: "tester",
      firebase_cli_token: ENV["FIREBASE_TOKEN"],
      release_notes: changelog
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
