# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(
        task: "test",
        gradle_path: "../gradlew"
    )
  end

  desc "Deploy a new development version to firebase distribution"
  lane :distribute do
    gradle(
        task: ":android-app:bundle",
        build_type: "Release",
        gradle_path: "../gradlew"
    )

    upload_to_play_store(
      track: "internal",
      aab: "./release/android-app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
